### ISSUE TITLE
No CORS header on 404 responses ?

### ISSUE THREAD

**Issue by charlesfleche** [aio-libs/aiohttp-cors#172]
I've registered my routes that way:

``` python
    cors = aiohttp_cors.setup(app, defaults={
        "*": aiohttp_cors.ResourceOptions(
            allow_credentials=True,
            expose_headers="*",
            allow_headers="*",
            allow_methods="*"
        )
    })
    for route in app.router.routes():
        cors.add(route)
```

However, the JS `fetch` API raises a CORS exception if I access a unkown URL.

``` js
const resp = await fetch('https://myapi.example.com/unknown/url') // raises a TypeError exception

// This code is never reached, but it would if resp had the CORS headers
resp.status === 404
resp.ok === false
```

What would be the recommended way to add CORS headers to `aiohttp` built-in 404 response ?

**Comment by asvetlov** [comment]
Who renders 404 page?

**Comment by charlesfleche** [comment]
The frontend will be responsible to render an appropriate error message: I'm using aiohttp for an API only, it only returns JSON.

**Comment by asvetlov** [comment]
My question is: what code sends 404 response on aiohttp side?

**Comment by charlesfleche** [comment]
Not my own code, so I guess it's a built-in feature of aiohttp: it must be a default response when an url does not match any of its routes.

**Comment by asvetlov** [comment]
`aiohttp-cors` doesn't catch builtin error page renderers, so it cannot modify their headers.
Perhaps it could be fixed by aiohttp.
As workaround you can add a middleware for custom error response sending like here: https://demos.aiohttp.org/en/latest/tutorial.html#middlewares

**Comment by charlesfleche** [comment]
OK, fair enough. Thanks @asvetlov
