### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [aio-libs/aiohttp-cors#196]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of GNU/Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code. With GPG signatures it is possible for packagers to verify source code releases quickly and easily.

In order to securely package your software I am kindly requesting GPG signatures for the source tarballs. If you are not yet familiar with secure source code signing I recommend using [GPGit](https://github.com/NicoHood/gpgit) which automates the process of secure source code signing and also has a quick start guide on GPG for learning how to use it manually.

Thanks in advance.

**Comment by asvetlov** [comment]
No.
The official PyPI position is: we don't need this feature.
See https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/ and https://github.com/pypa/warehouse/issues/3356 (as very many articles/issues about GPG  signing on PyPI).

**Comment by NicoHood** [comment]
Any updates on this?

**Comment by asvetlov** [comment]
You need to convince not me but PyPI team

**Comment by NicoHood** [comment]
No, I need to convince you. Because the distribution packages do not use pypi, they use your sources published on github. And those can be verified, if gpg signatures are provided and it would help us a lot.

I'd love to bring homeassistant to the official archlinux repository, but my personal requirement for this is to have all dependencies gpg signed - for the security of all users and my responsiblity. And your package is one of those dependencies.

**Comment by asvetlov** [comment]
Sorry, the answer is no.
GPG signing requires changing our autodeployment process, I don't want to touch it.
Say again, if PyPI is not secure enough to your requirements -- please convince its maintainers to raise up the protection level.
I don't want to do an extra work unless it the work is required.

**Comment by NicoHood** [comment]
I understand that you want to avoid additional work.

Uploading an additioal, signed tarfile should be not much of work though and integrate with your current workflow. Even gpgit can handle existing git tags and upload signed archived automated to github. It cant get easier than that.
