### ISSUE TITLE
Wildcard ports for localhost 

### ISSUE THREAD

**Issue by cassieramen** [aio-libs/aiohttp-cors#237]
I'm wondering if there is a way for me to use a regex to allow any localhost ports to be allowed? 

Something like: 
```
"http://localhost:[0-9]*": aiohttp_cors.ResourceOptions(
    expose_headers="*",
    allow_headers="*",
)
```

**Comment by asvetlov** [comment]
I'm wondering if `localhost` makes sense for CORS at all.
What is your use case?

**Comment by cassieramen** [comment]
We have two different api services we use for a single site. For local development we'd like to be able to run the site at something like port 3000 and talk to a locally hosted web api at port 9000 or at our staging environment. 

We can fix the localhost port we run the site on but I'd strongly prefer to not care.

**Comment by yzhang1994** [comment]
Also need this for testing API on localhost.

**Comment by asvetlov** [comment]
You can pass used port explicitly to aiohttp_cors on an applicaiton initialization.
Like people usually use different databases for production and testing environments.
There is no need to tweak on the library level.

**Comment by bman7777** [comment]
what if I want to allow CORS on all subdomains (e.g. `*.google.com`) ? Is there any wildcard or regex support I can use?
