### ISSUE TITLE
Class based views are not supported

### ISSUE THREAD

**Issue by trivigy** [aio-libs/aiohttp-cors#41]
When using web.View as the handler if the route being added for '*' then cors doesn't work because the server seems not to be able to find the OPTIONS. Not sure why that is, I didn't take the time to investigate but my guess is that the \* end up taking priority and the routing goes to the \* handler instead of the CORS handler.

**Comment by rutsky** [comment]
@trivigy thank you for posting this bug report and sorry for the long delay.

Yes, as I see `*` handler from class based view's (CBV) takes precedence over `OPTIONS` handler being added by aiohttp-cors, and I don't see easy way to handle CBV classes in aiohttp-cors so currently it will not work with them.

Perhaps best solution will be to introduce aiohttp-cors mixin for CBV which will handle `OPTIONS` and require users to inherit from it, like:

```
# Not implemented yet
from aiohttp_cors import ViewMixin

class MyView(ViewMixin, web.View):
    async def get(self):
        return await get_resp(self.request)

    async def post(self):
        return await post_resp(self.request)
```

**Comment by asvetlov** [comment]
Makes sense

**Comment by balloob** [comment]
I am using the following workaround to register my classes so that they work with aiohttp_cors:

```python
def register_view(app, url, view):
    for method in ('get', 'post', 'delete', 'put'):
        handler = getattr(view, method, None)

        if not handler:
            continue

        app.router.add_route(method, url, handler)
```

**Comment by rutsky** [comment]
@balloob will `aiohttp_cors.ViewMixin` mixin will help you if it will be implemented in `aiohttp_cors`?

**Comment by balloob** [comment]
Probably - but I was already using views in a weird way: I wanted to instantiate the views before registering them so I could keep a reference to the state of the house (I'm working on [Home Assistant](https://github.com/home-assistant/home-assistant)). So I actually had a `__call__` method on my instantiated view that would handle the routing to get/post etc. (I know that it's not the right way but we're transitioning from CherryPi WSGI server + Werkzeug and getting it to work is the first step.)

**Comment by asvetlov** [comment]
@balloob if you want to instantiate your view classes before registering you don't need `aiohttp.web.View` at all -- custom classes may serve everything perfectly.

**Comment by trivigy** [comment]
@rutsky Thanks for the suggestion. Took me a long time to notice that you responded. I actually use a very custom implementation of the View within our system. I personally wanted to add a whole lot more functionalities to the view and therefore re-implemented it. Had to override add_route() functions and all. Therefore this problem was never an issue for my systems but it was certainly a bug worth reporting.

**Comment by buhman** [comment]
@balloob's hack works ok for me as well, but I think a ViewMixin would be better.

**Comment by asvetlov** [comment]
Guys, we need a champion for the issue.
Do anybody want work on PR?

**Comment by rutsky** [comment]
I recently changed job, moved to another country and on paternity leave right now, so I don't have free time right now, sorry.

**Comment by pedrokiefer** [comment]
@asvetlov @rutsky would please review my PR?

**Comment by asvetlov** [comment]
Let me setup coverage tools first, I'll return to review after that.

**Comment by pedrokiefer** [comment]
👍 💯
