### ISSUE TITLE
Rename `aiohttp_cors` package to `aiohttp-cors`

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiohttp-cors#53]
See #43 for reasoning.

@asvetlov thanks for making the change c34202e.

In order to complete renameing we need to:

* [x] rename package in sources (c34202e)
* [x] rename GitHub repository
* [x] test that this change will not break anything (if it will, it's OK, but we need to explicitly state that)
* [ ] add notice to change log
* [ ] rename package on PyPI (how?)
* [ ] publish renamed package (last time I released aiohttp-cors I worked on publishing to PyPI from Travis: it should be enough to push master branch with tag in order to force uploading on PyPI)

@asvetlov which parts you want to complete by yourself right now and which part can you want to delegate to me (during this week)?

**Comment by asvetlov** [comment]
* `pip install aiohttp_cors` is still working but `pip install aiohttp-cors` is preferable way. I've tested it for other aio-libs projects.
* Change log notice? Please do
* It's impossible to rename PyPI package AFAIK but just uploading new version works fine.

Both pip and PyPI have transparent processing for names with `_` and `-`, nothing is broken.
It's pretty much cosmetic changes to follow recommended names (and fix packaging tool for Fedora).

**Comment by asvetlov** [comment]
Done
