### ISSUE TITLE
aiohttp 2.0+ support?

### ISSUE THREAD

**Issue by trivigy** [aio-libs/aiohttp-cors#81]
Just wanted to know if there is a particular issue why it was restricted to aiohttp <2.0. Was it simply not passing the unittests or someone just needs to thoroughly check unittests and compatibility?

**Comment by trivigy** [comment]
@rutsky I am happy to look into this and figure what needs to be fixed for 2.0 support. I want to move to aiohttp 2.0+ on my system and this one is a blocker. Noticed that you mentioned this will be supported in next release but I figured I'll ask when that might happen.

**Comment by rutsky** [comment]
@trivigy looks like there were only issues in tests. Let's wait for #82 CI completion and I'll do aiohttp_cors 0.5.2 release that will require `aiohttp>=1.1`.

@trivigy can you try previous aiohttp_cors (`0.5.0`) release with aiohttp 2.0? I think it should work with aiohttp 2.0, but I haven't thoroughly checked changes in aiohttp 2.0.

**Comment by rutsky** [comment]
@trivigy aiohttp_cors 0.5.2 with aiohttp 2.0 support released, please give it a try!

**Comment by trivigy** [comment]
@rutsky Thanks a lot!!! I appreciate the quick turn over. Let me know if you ever need anything.
